//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_OOP_demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadon
    {
        public int INDEX { get; set; }
        public Nullable<int> ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> QUANTITES { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
    
        public virtual OOP_project OOP_project { get; set; }
    }
}
